// Data kartu tarot
const tarotCards = [
    { name: "The Fool", meaning: "Awal baru, petualangan, kemungkinan tak terbatas", symbol: "🃏" },
    { name: "The Magician", meaning: "Kreativitas, keterampilan, kemampuan manifestasi", symbol: "✨" },
    { name: "The High Priestess", meaning: "Intuisi, pengetahuan bawah sadar, misteri", symbol: "🌙" },
    { name: "The Empress", meaning: "Kesuburan, kelimpahan, keibuan, alam", symbol: "🌿" },
    { name: "The Emperor", meaning: "Otoritas, struktur, kepemimpinan, kestabilan", symbol: "👑" },
    { name: "The Hierophant", meaning: "Tradisi, konformitas, kepercayaan, bimbingan", symbol: "🔑" },
    { name: "The Lovers", meaning: "Cinta, harmoni, pilihan, hubungan", symbol: "❤️" },
    { name: "The Chariot", meaning: "Kontrol, kemauan, kemenangan, tekad", symbol: "🏆" },
    { name: "Strength", meaning: "Keberanian, kesabaran, pengaruh, kasih sayang", symbol: "🦁" },
    { name: "The Hermit", meaning: "Introspeksi, pencarian, bimbingan dalam", symbol: "🔦" },
    { name: "Wheel of Fortune", meaning: "Perubahan, siklus, keberuntungan, takdir", symbol: "🎡" },
    { name: "Justice", meaning: "Keadilan, kebenaran, hukum, keseimbangan", symbol: "⚖️" },
    { name: "The Hanged Man", meaning: "Pengorbanan, perspektif baru, menunggu", symbol: "🙃" },
    { name: "Death", meaning: "Akhir, transformasi, perubahan, transisi", symbol: "🦋" },
    { name: "Temperance", meaning: "Keseimbangan, moderasi, kesabaran, tujuan", symbol: "🌈" },
    { name: "The Devil", meaning: "Keterikatan, materialisme, ketergantungan", symbol: "⛓️" },
    { name: "The Tower", meaning: "Kekacauan, pengungkapan tiba-tiba, pembebasan", symbol: "⚡" },
    { name: "The Star", meaning: "Harapan, inspirasi, ketenangan, kemurahan hati", symbol: "⭐" },
    { name: "The Moon", meaning: "Ilusi, ketakutan, kecemasan, ketidakpastian", symbol: "🌕" },
    { name: "The Sun", meaning: "Sukacita, keberhasilan, vitalitas, kebahagiaan", symbol: "☀️" },
    { name: "Judgement", meaning: "Kebangkitan, pembaruan, evaluasi, penilaian", symbol: "📯" },
    { name: "The World", meaning: "Penyelesaian, integrasi, pencapaian, perjalanan", symbol: "🌍" },
    { name: "Ace of Wands", meaning: "Kreativitas, inspirasi, kekuatan baru", symbol: "🔥" },
    { name: "King of Cups", meaning: "Kecerdasan emosional, keseimbangan, diplomasi", symbol: "🏆" },
    { name: "Queen of Swords", meaning: "Kejujuran, kemandirian, kecerdasan", symbol: "⚔️" },
    { name: "Knight of Pentacles", meaning: "Kerja keras, tanggung jawab, kesabaran", symbol: "🛡️" },
    { name: "Page of Wands", meaning: "Petualangan, kegairahan, eksplorasi", symbol: "🧭" },
    { name: "Ten of Cups", meaning: "Kebahagiaan keluarga, cinta, harmoni", symbol: "🌈" },
    { name: "Nine of Swords", meaning: "Kecemasan, kekhawatiran, ketakutan", symbol: "😰" },
    { name: "Eight of Pentacles", meaning: "Pembelajaran, kerajinan, kesempurnaan", symbol: "🔨" },
    { name: "Seven of Wands", meaning: "Tantangan, persaingan, pertahanan", symbol: "🛡️" },
    { name: "Six of Cups", meaning: "Nostalgia, kenangan, masa kecil", symbol: "🌹" },
    { name: "Five of Swords", meaning: "Konflik, kehilangan, kekalahan", symbol: "⚔️" },
    { name: "Four of Pentacles", meaning: "Keamanan, konservasi, ketamakan", symbol: "💰" },
    { name: "Three of Wands", meaning: "Ekspansi, perencanaan jangka panjang", symbol: "🔭" },
    { name: "Two of Cups", meaning: "Kemitraan, ketertarikan, hubungan", symbol: "❤️" }
];