# tarot.py

TAROT_DECK = [
    # Major Arcana
    {"name": "The Fool",           "upright": "awal baru, keberanian, petualangan",                 "reversed": "kecerobohan, keragu-raguan, stagnasi",              "image": "major_arcana_fool"},
    {"name": "The Magician",      "upright": "kreativitas, inisiatif, kemampuan",                "reversed": "manipulasi, ketidakjujuran, kurang fokus",         "image": "major_arcana_magician"},
    {"name": "The High Priestess","upright": "intuisi, rahasia, kebijaksanaan batin",           "reversed": "penolakan intuisi, kebingungan, rahasia terungkap","image": "major_arcana_priestess"},
    {"name": "The Empress",       "upright": "kesuburan, kelimpahan, kreativitas",               "reversed": "ketergantungan, cemburu, stagnasi",              "image": "major_arcana_empress"},
    {"name": "The Emperor",       "upright": "otoritas, stabilitas, struktur",                  "reversed": "kekakuan, tirani, penyalahgunaan kekuasaan",     "image": "major_arcana_emperor"},
    {"name": "The Hierophant",    "upright": "tradisi, ajaran, bimbingan",                     "reversed": "dogma, pemberontakan, kebingungan spiritual",     "image": "major_arcana_hierophant"},
    {"name": "The Lovers",        "upright": "cinta, hubungan, pilihan penting",                 "reversed": "konflik, keraguan, ketidakseimbangan",          "image": "major_arcana_lovers"},
    {"name": "The Chariot",       "upright": "kendali, kemenangan, kemauan kuat",               "reversed": "kehilangan kendali, agresi, hambatan",         "image": "major_arcana_chariot"},
    {"name": "Strength",          "upright": "keberanian, kesabaran, belas kasih",               "reversed": "keraguan diri, kelemahan, ketidakseimbangan emosional","image": "major_arcana_strength"},
    {"name": "The Hermit",        "upright": "introspeksi, pencarian batin, kebijaksanaan",     "reversed": "isolasi, kesendirian, stagnasi",               "image": "major_arcana_hermit"},
    {"name": "Wheel of Fortune",  "upright": "perubahan, nasib, kesempatan",                   "reversed": "resistensi perubahan, kemalangan, kebingungan", "image": "major_arcana_fortune"},
    {"name": "Justice",           "upright": "keseimbangan, keadilan, kebenaran",               "reversed": "ketidakadilan, ketidakjujuran, ketidakseimbangan","image": "major_arcana_justice"},
    {"name": "The Hanged Man",    "upright": "pengorbanan, perspektif baru, penyerahan",        "reversed": "keterlambatan, stagnasi, penolakan",          "image": "major_arcana_hanged"},
    {"name": "Death",             "upright": "transformasi, akhir, awal baru",                  "reversed": "resistensi perubahan, stagnasi, ketakutan",    "image": "major_arcana_death"},
    {"name": "Temperance",        "upright": "keseimbangan, moderasi, kesabaran",               "reversed": "ekstrem, ketidakseimbangan, keserakahan",        "image": "major_arcana_temperance"},
    {"name": "The Devil",         "upright": "keterikatan, nafsu, ketergantungan",              "reversed": "pemulihan, kebebasan, pelepasan",               "image": "major_arcana_devil"},
    {"name": "The Tower",         "upright": "perubahan mendadak, pencerahan, kehancuran",       "reversed": "penolakan perubahan, penundaan, ketakutan",     "image": "major_arcana_tower"},
    {"name": "The Star",          "upright": "harapan, inspirasi, penyembuhan",                "reversed": "keputusasaan, kurang inspirasi, rasa bersalah", "image": "major_arcana_star"},
    {"name": "The Moon",          "upright": "ilusi, intuisi, emosi dalam",                    "reversed": "kebingungan, ketakutan, kesalahpahaman",       "image": "major_arcana_moon"},
    {"name": "The Sun",           "upright": "kebahagiaan, sukses, vitalitas",                "reversed": "keraguan, energi tertutup, kelelahan",        "image": "major_arcana_sun"},
    {"name": "Judgement",         "upright": "evaluasi, kebangkitan, panggilan batin",          "reversed": "keraguan, stagnasi, penolakan perubahan",      "image": "major_arcana_judgement"},
    {"name": "The World",         "upright": "kelengkapan, pencapaian, penyelesaian",          "reversed": "penundaan akhir, ketidaklengkapan, stagnasi", "image": "major_arcana_world"},

    # Cups (Minor Arcana)
    {"name": "Ace of Cups",       "upright": "awal emosional baru, cinta murni, kedamaian",   "reversed": "blok emosi, kesedihan, ketidakmampuan membuka hati", "image": "minor_arcana_cups_ace"},
    {"name": "Two of Cups",       "upright": "kemitraan, cinta, keselarasan emosi",           "reversed": "ketidakharmonisan, konflik, ketidakpastian",    "image": "minor_arcana_cups_2"},
    {"name": "Three of Cups",     "upright": "perayaan, persahabatan, komunitas",            "reversed": "cemburu, perpisahan, isolasi",               "image": "minor_arcana_cups_3"},
    {"name": "Four of Cups",      "upright": "kebosanan, introspeksi, peluang terlewat",      "reversed": "kesadaran peluang baru, penghargaan, motivasi", "image": "minor_arcana_cups_4"},
    {"name": "Five of Cups",      "upright": "penyesalan, kehilangan, kesedihan",              "reversed": "pemulihan, pelepasan, harapan baru",           "image": "minor_arcana_cups_5"},
    {"name": "Six of Cups",       "upright": "nostalgia, kenangan, kebaikan masa lalu",        "reversed": "terjebak masa lalu, penyesalan, stagnasi emosional","image": "minor_arcana_cups_6"},
    {"name": "Seven of Cups",     "upright": "imajinasi, banyak pilihan, ilusi",              "reversed": "kebingungan, terlalu banyak opsi, penipuan",   "image": "minor_arcana_cups_7"},
    {"name": "Eight of Cups",     "upright": "meninggalkan, perjalanan batin, pencarian makna", "reversed": "penolakan perubahan, penyesalan, kemalasan",      "image": "minor_arcana_cups_8"},
    {"name": "Nine of Cups",      "upright": "kepuasan, pencapaian emosional, kebahagiaan",    "reversed": "keserakahan, ketidakpuasan, kekecewaan",      "image": "minor_arcana_cups_9"},
    {"name": "Ten of Cups",       "upright": "kebahagiaan keluarga, harmoni, cinta sejati",      "reversed": "konflik keluarga, ketidakbahagiaan, kekecewaan","image": "minor_arcana_cups_10"},
    {"name": "Page of Cups",      "upright": "berita emosional, kreativitas, intuisi",         "reversed": "ketidakdewasaan emosional, ketidakpastian, gosip", "image": "minor_arcana_cups_page"},
    {"name": "Knight of Cups",    "upright": "romantisme, petualangan emosional, idealisme",  "reversed": "kekecewaan, ketidakteraturan, ilusi",         "image": "minor_arcana_cups_knight"},
    {"name": "Queen of Cups",     "upright": "empati, kelembutan, intuisi tajam",            "reversed": "emosional berlebih, kerentanan, over-sensitif",   "image": "minor_arcana_cups_queen"},
    {"name": "King of Cups",      "upright": "pengendalian emosional, kebijaksanaan, dukungan","reversed": "manipulasi emosional, ketidakstabilan, dingin",  "image": "minor_arcana_cups_king"},

    # Swords (Minor Arcana)
    {"name": "Ace of Swords",     "upright": "kebenaran, kemenangan mental, kejelasan",      "reversed": "keraguan, kegagalan komunikasi, kebingungan",  "image": "minor_arcana_swords_ace"},
    {"name": "Two of Swords",     "upright": "keputusan sulit, keseimbangan, penyeimbangan","reversed": "keraguan, konflik batin, ketidakstabilan",      "image": "minor_arcana_swords_2"},
    {"name": "Three of Swords",   "upright": "kesedihan, pengkhianatan, patah hati",         "reversed": "pemulihan hati, pengampunan",                  "image": "minor_arcana_swords_3"},
    {"name": "Four of Swords",    "upright": "istirahat, kontemplasi, pemulihan",            "reversed": "kebosanan, kecemasan, stagnasi",                "image": "minor_arcana_swords_4"},
    {"name": "Five of Swords",    "upright": "konflik, kemenangan pahit, persaingan",        "reversed": "penyesalan, rekonsiliasi",                     "image": "minor_arcana_swords_5"},
    {"name": "Six of Swords",     "upright": "transisi, perjalanan, pemulihan",             "reversed": "resistensi perubahan, ketakutan, stagnasi",     "image": "minor_arcana_swords_6"},
    {"name": "Seven of Swords",   "upright": "kecerdikan, strategi, kerahasiaan",            "reversed": "ketahuan, penyesalan, kehilangan",                "image": "minor_arcana_swords_7"},
    {"name": "Eight of Swords",   "upright": "rasa terkurung, batasan mental, ketakutan",   "reversed": "pembebasan, kejelasan, keberanian",             "image": "minor_arcana_swords_8"},
    {"name": "Nine of Swords",    "upright": "kecemasan, mimpi buruk, kesedihan",          "reversed": "pemulihan kecemasan, harapan baru",           "image": "minor_arcana_swords_9"},
    {"name": "Ten of Swords",     "upright": "akhir menyakitkan, kekalahan, penyerahan",   "reversed": "pemulihan, harapan baru, pengampunan",        "image": "minor_arcana_swords_10"},
    {"name": "Page of Swords",    "upright": "intelijensi, keingintahuan, komunikasi",    "reversed": "gosip, kebingungan, ketidakdewasaan",           "image": "minor_arcana_swords_page"},
    {"name": "Knight of Swords",  "upright": "tindakan cepat, keberanian, agresi terarah",  "reversed": "impulsif, konflik, ketidakstabilan",           "image": "minor_arcana_swords_knight"},
    {"name": "Queen of Swords",   "upright": "kejernihan pikiran, kejujuran, independensi","reversed": "dingin, sarkasme, keputusasaan",               "image": "minor_arcana_swords_queen"},
    {"name": "King of Swords",    "upright": "logika, keadilan, otoritas intelektual",     "reversed": "penyalahgunaan kekuasaan, kejam, tidak berempati","image": "minor_arcana_swords_king"},

    # Wands (Minor Arcana)
    {"name": "Ace of Wands",      "upright": "awal kreatif, inspirasi, energi baru",      "reversed": "kekecewaan, kurang motivasi, penghambatan",    "image": "minor_arcana_wands_ace"},
    {"name": "Two of Wands",      "upright": "perencanaan, visi jangka panjang, keputusan",    "reversed": "ketakutan mengambil risiko, kebuntuan",         "image": "minor_arcana_wands_2"},
    {"name": "Three of Wands",    "upright": "ekspansi, peluang, eksplorasi",              "reversed": "penundaan, pembatasan, keraguan",           "image": "minor_arcana_wands_3"},
    {"name": "Four of Wands",     "upright": "perayaan, stabilitas, komunitas",             "reversed": "ketidakstabilan, konflik, gangguan",           "image": "minor_arcana_wands_4"},
    {"name": "Five of Wands",     "upright": "perselisihan, persaingan, dinamis konflik",     "reversed": "rekonsiliasi, kerjasama, penyelesaian",           "image": "minor_arcana_wands_5"},
    {"name": "Six of Wands",      "upright": "keberhasilan, pengakuan, kemenangan publik",    "reversed": "kesombongan, keraguan, kegagalan publik",       "image": "minor_arcana_wands_6"},
    {"name": "Seven of Wands",    "upright": "pertahanan, ketahanan, keberanian bertahan",    "reversed": "keraguan, mundur, keraguan diri",               "image": "minor_arcana_wands_7"},
    {"name": "Eight of Wands",    "upright": "percepatan, komunikasi cepat, pergerakan",    "reversed": "penundaan, miskomunikasi, hambatan",           "image": "minor_arcana_wands_8"},
    {"name": "Nine of Wands",     "upright": "ketahanan, proteksi, kewaspadaan",            "reversed": "kelelahan, keraguan terakhir, terlalu berhati-hati", "image": "minor_arcana_wands_9"},
    {"name": "Ten of Wands",      "upright": "beban, tanggung jawab, tekanan",              "reversed": "kelebihan beban, burnout, dilepaskan",        "image": "minor_arcana_wands_10"},
    {"name": "Page of Wands",     "upright": "antusiasme, penemuan, semangat muda",          "reversed": "ketidakstabilan, kemunduran, keraguan awal",     "image": "minor_arcana_wands_page"},
    {"name": "Knight of Wands",   "upright": "petualangan, keberanian, inspirasi spontan",   "reversed": "impulsif, kedangkalan, kerusuhan",              "image": "minor_arcana_wands_knight"},
    {"name": "Queen of Wands",    "upright": "kepemimpinan, karisma, kepercayaan diri",      "reversed": "dominasi, egosentris, cemburu",               "image": "minor_arcana_wands_queen"},
    {"name": "King of Wands",     "upright": "visibilitas, visi, keberanian memimpin",       "reversed": "dominasi berlebihan, kekacauan, kehilangan kendali", "image": "minor_arcana_wands_king"},

    # Pentacles (Minor Arcana)
    {"name": "Ace of Pentacles",  "upright": "peluang material baru, kemakmuran",        "reversed": "kerugian, kesempatan terlewat, keserakahan",  "image": "minor_arcana_pentacles_ace"},
    {"name": "Two of Pentacles",  "upright": "penyesuaian, fleksibilitas, keseimbangan uang", "reversed": "ketidakstabilan finansial, stres, kebingungan", "image": "minor_arcana_pentacles_2"},
    {"name": "Three of Pentacles","upright": "kerjasama, kualitas, dedikasi kerja",        "reversed": "kurang kolaborasi, ego tim, kualitas rendah",   "image": "minor_arcana_pentacles_3"},
    {"name": "Four of Pentacles", "upright": "stabilitas, penghematan, keamanan",          "reversed": "kekikiran, ketakutan kehilangan, sifat militan", "image": "minor_arcana_pentacles_4"},
    {"name": "Five of Pentacles", "upright": "kesulitan finansial, keterbatasan, kerugian",   "reversed": "pemulihan finansial, dukungan, pengampunan",  "image": "minor_arcana_pentacles_5"},
    {"name": "Six of Pentacles",  "upright": "kedermawanan, bantuan, keseimbangan pemberian",  "reversed": "ketergantungan, ketidakseimbangan, belas kasihan palsu","image": "minor_arcana_pentacles_6"},
    {"name": "Seven of Pentacles","upright": "evaluasi hasil, ketekunan, kesabaran",        "reversed": "ketidakpuasan, keraguan dalam usaha, malas",  "image": "minor_arcana_pentacles_7"},
    {"name": "Eight of Pentacles","upright": "pengembangan keterampilan, pelatihan, kerja keras","reversed": "kelelahan, perfeksionisme berlebih, bosan kerja",   "image": "minor_arcana_pentacles_8"},
    {"name": "Nine of Pentacles", "upright": "kemandirian, kemakmuran, kenikmatan material",  "reversed": "ketergantungan, isolasi, keserakahan",      "image": "minor_arcana_pentacles_9"},
    {"name": "Ten of Pentacles",  "upright": "warisan, stabilitas keluarga, keberhasilan ekonomi","reversed": "masalah keluarga, kerugian finansial, konflik warisan", "image": "minor_arcana_pentacles_10"},
    {"name": "Page of Pentacles", "upright": "peluang belajar, aspirasi material, penelitian","reversed": "ketidakfokusan, keengganan belajar, pemborosan",  "image": "minor_arcana_pentacles_page"},
    {"name": "Knight of Pentacles","upright": "ketekunan, tanggung jawab, stabilitas kerja",    "reversed": "kebosanan, kekakuan, keengganan risiko",      "image": "minor_arcana_pentacles_knight"},
    {"name": "Queen of Pentacles", "upright": "perawatan, keseimbangan, keamanan finansial",    "reversed": "ketergantungan, kekurangan perhatian, materialisme berlebihan","image": "minor_arcana_pentacles_queen"},
    {"name": "King of Pentacles",  "upright": "kekuasaan finansial, stabilitas, keberhasilan bisnis","reversed": "keserakahan, keserakahan, penyalahgunaan kekuasaan", "image": "minor_arcana_pentacles_king"},
]

# Fungsi untuk memuat gambar atau menangani pemilihan kartu tarot
# Dapat ditambahkan sesuai kebutuhan aplikasi Anda